<?php

$hierarchy = umiHierarchy::getInstance();
foreach($variables["lines"] as $item) {
   $element = $hierarchy->getElement($item['id']);

?>

  <div class="card hover-shadow-7 my-8">
          <div class="row">
            <div class="col-md-4">
              <a href="blog-single.html">
              <img class="fit-cover position-absolute h-100" src="<?= $image = $this->macros('system', 'makeThumbnailFull', array('path' => '.' .  $element->getValue("anons_pic"), 'width' => 285, 'height' => 268))["src"]?>" alt="..."></a>
            </div>
            <div class="col-md-8">
              <div class="p-7">
                <h4><?= $element->getValue('h1') ?></h4>
                <p><?= mb_strimwidth($element->getValue('anons'), 0, 150) . "..."?></p>
                <a class="small ls-1" href="<?= $item['link'] ?>">Read More <span class="pl-1">&xrarr;</span></a>
              </div>
            </div>
          </div>
        </div>
<?}
?>