<?php
//Получить новость
$item = $this->getPageById($variables['id']);
//Если у новости есть картинка анонса - сделать кроп
if ($img = $item->anons_pic) {
    $thumb = $this->macros('system', 'makeThumbnailFull', array('path' => $img->getFilePath(), 'width' => 285, 'height' => 268, 'crop' => 1, 'cropside' => 9));
}
?>

<div class="card hover-shadow-7 my-8">
    <div class="row">
        <?= (empty($img)) ? '' : '
            <div class="col-md-4">
                <a href="' . $variables['link'] . '"><img class="fit-cover position-absolute h-100" src="' . $thumb['filepath'] . '" alt="' . $img->getAlt() . '"></a>
            </div>
            ' ?>
        <div class="col-md-8">
            <div class="p-7">
                <h4><?= $variables['name']; ?></h4>
                <p><?= $this->getPageById($variables['id'])->anons; ?>
                    <a class="small ls-1" href="<?= $variables['link'] ?>">Read More <span
                                class="pl-1">&xrarr;</span></a>
            </div>
        </div>
    </div>
</div>
