<div class="section" id="section-content">
    <div class="container">

        <div class="row">
            <div class="col-lg-8 mx-auto">

                <?=$variables['page']->content;?>

            </div>
        </div>

    </div>
</div>

<?php
//Получить идентификатор автора текущей страницы
$author = $variables['page']->getValue('author');
echo $this->render($author, 'modules/news/items-by-author.phtml');
?>