<?php 
$page = $variables['page'];

echo $this->render($variables, 'blocks/pagetitle');

if($page->getIsDefault()) {
	echo $this->render($variables, 'modules/content/main');
}elseif(file_exists('./templates/default/php/modules/content/content-'.$news->getObjectTypeId().'.phtml')) {{
	echo $this->render($variables, 'modules/content/content-'.$page->getObjectTypeId());
}else{
	echo $this->render($variables, 'modules/content/default');
}

?>