<?php

$news = new selector('pages');
$news->limit(0, 5)->types('hierarchy-type')->name('news', 'item');

$result = $news->result();

?>

<section class="section bg-gray p-0">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-xl-9 mx-auto">

				<?php foreach ($result as $item) {
					$image = $this->macros(
						'system',
						'makeThumbnailFull',
						array($item->anons_pic->getFilePath(), 285, 268)
					);
					?>
                    <div class="card hover-shadow-7 my-8">
                        <div class="row">
                            <div class="col-md-4" style="height: 268px">
                                <a href="<?= $item->link ?>"><img
                                            class="fit-cover position-absolute h-100"
                                            src="<?= $image['filepath'] ?>" alt="..."></a>
                            </div>

                            <div class="col-md-8" style="height: 268px">
                                <div class="px-7 py-6">
                                    <h4><?= $item->h1 ?></h4>
                                    <p style="max-height: 80px; overflow: hidden">
                                        <?= strip_tags($item->anons) ?>
                                    </p>
                                    <a class="small ls-1" href="<?= $item->link ?>">Read More <span
                                                class="pl-1">&xrarr;</span></a>
                                </div>
                            </div>
                        </div>
                    </div>


				<?php } ?>

                <nav class="flexbox my-8">
                    <a class="btn btn-white disabled"><i class="ti-arrow-left fs-9 mr-2"></i> Newer</a>
                    <a class="btn btn-white" href="#">Older <i class="ti-arrow-right fs-9 ml-2"></i></a>
                </nav>

            </div>
        </div>
    </div>
</section>

<div class="section bg-gray">
    <div class="container">


        <div class="row">

            <div class="col-lg-8 mx-auto">
                <h2>Feedback</h2>

                <form action="/" method="POST" data-form="mailer">

                    <div class="row">
                        <div class="form-group col-12 col-md-6">
                            <input class="form-control" type="text" name="name" placeholder="Name" required>
                        </div>

                        <div class="form-group col-12 col-md-6">
                            <input class="form-control" type="email" name="email" placeholder="Email" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <textarea class="form-control" name="message" placeholder="Comment" rows="4" required>
                        </textarea>
                    </div>

                    <button class="btn btn-primary btn-block" type="submit">Submit your comment</button>
                </form>

            </div>
        </div>

    </div>
</div>

