<?= $this->render($this->macros('news', 'lastlist', array('blog', null, 5, true)), 'modules/news/items-on-root'); ?>

    <div class="section bg-gray">
        <div class="container">


            <div class="row">

                <div class="col-lg-8 mx-auto">
                    <h2>Feedback</h2>

                    <form action="" method="POST">

                        <div class="row">
                            <div class="form-group col-12 col-md-6">
                                <input name="name" class="form-control" type="text" placeholder="Name" required>
                            </div>

                            <div class="form-group col-12 col-md-6">
                                <input name="email" class="form-control" type="text" placeholder="Email" required>
                            </div>
                        </div>


                        <div class="form-group">
                            <textarea name="comment" class="form-control" placeholder="Comment" rows="4"
                                      required></textarea>
                        </div>

                        <button class="btn btn-primary btn-block" type="submit">Submit your comment</button>
                    </form>

                </div>
            </div>

        </div>
    </div>

<?php
$name = filter_input(INPUT_POST, 'name', FILTER_SANITIZE_STRING);
$email = filter_input(INPUT_POST, 'email', FILTER_VALIDATE_EMAIL);
$comment = filter_input(INPUT_POST, 'comment', FILTER_SANITIZE_STRING);

if (!empty($name) and !empty($email) and !empty($comment)) {
    $mail = new umiMail;
    //Выставляем получателей письма
    $mail->addRecipient("admin@testtask.madex.pro", "Администратор");

    //Указываем, от чьего имени придет письмо
    $mail->setFrom("admin@testtask.madex.pro", "Администратор");

    //Устанавливаем содержание письма
    $mail->setContent("Пользовать {$name} запросил обратную связь по почте {$email} с комментарием {$comment}");

    //Устанавливаем тему письма
    $mail->setSubject('Обратная связь');

    //Подтверждаем отправку письма
    $mail->commit();

    //Отправляем письмо. Если не выполнить send(), то письмо все равно отправится. Но где-то во время завершения работы скрипта.
    $mail->send();
}
