<section class="section bg-gray p-0">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-xl-9 mx-auto">


                <div class="card hover-shadow-7 my-8">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="blog-single.html"><img class="fit-cover position-absolute h-100" src="/templates/default/assets/img/thumb/2.jpg" alt="..."></a>
                        </div>

                        <div class="col-md-8">
                            <div class="p-7">
                                <h4>Top 5 brilliant content marketing strategies</h4>
                                <p>Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text to build on the card title.</p>
                                <a class="small ls-1" href="blog-single.html">Read More <span class="pl-1">&xrarr;</span></a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="card hover-shadow-7 my-8">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="blog-single.html"><img class="fit-cover position-absolute h-100" src="/templates/default/assets/img/thumb/3.jpg" alt="..."></a>
                        </div>

                        <div class="col-md-8">
                            <div class="p-7">
                                <h4>Best practices for minimalist design with example</h4>
                                <p>Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text to build on the card title.</p>
                                <a class="small ls-1" href="blog-single.html">Read More <span class="pl-1">&xrarr;</span></a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="card hover-shadow-7 my-8">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="blog-single.html"><img class="fit-cover position-absolute h-100" src="/templates/default/assets/img/thumb/4.jpg" alt="..."></a>
                        </div>

                        <div class="col-md-8">
                            <div class="p-7">
                                <h4>Congratulate and thank to Maryam for joining our team</h4>
                                <p>Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text to build on the card title.</p>
                                <a class="small ls-1" href="blog-single.html">Read More <span class="pl-1">&xrarr;</span></a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="card hover-shadow-7 my-8">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="blog-single.html"><img class="fit-cover position-absolute h-100" src="/templates/default/assets/img/thumb/5.jpg" alt="..."></a>
                        </div>

                        <div class="col-md-8">
                            <div class="p-7">
                                <h4>New published books to read by a product designer</h4>
                                <p>Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text to build on the card title.</p>
                                <a class="small ls-1" href="blog-single.html">Read More <span class="pl-1">&xrarr;</span></a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="card hover-shadow-7 my-8">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="blog-single.html"><img class="fit-cover position-absolute h-100" src="/templates/default/assets/img/thumb/6.jpg" alt="..."></a>
                        </div>

                        <div class="col-md-8">
                            <div class="p-7">
                                <h4>This is why it's time to ditch dress codes at work</h4>
                                <p>Some quick example text to build on the card title and make up the bulk of the card's content. Some quick example text to build on the card title.</p>
                                <a class="small ls-1" href="blog-single.html">Read More <span class="pl-1">&xrarr;</span></a>
                            </div>
                        </div>
                    </div>
                </div>



                <nav class="flexbox my-8">
                    <a class="btn btn-white disabled"><i class="ti-arrow-left fs-9 mr-2"></i> Newer</a>
                    <a class="btn btn-white" href="#">Older <i class="ti-arrow-right fs-9 ml-2"></i></a>
                </nav>

            </div>
        </div>
    </div>
</section>

<div class="section bg-gray">
    <div class="container">


        <div class="row">

            <div class="col-lg-8 mx-auto">
                <h2>Feedback</h2>

                <form action="#" method="POST">

                    <div class="row">
                        <div class="form-group col-12 col-md-6">
                            <input class="form-control" type="text" placeholder="Name">
                        </div>

                        <div class="form-group col-12 col-md-6">
                            <input class="form-control" type="text" placeholder="Email">
                        </div>
                    </div>

                    <div class="form-group">
                        <textarea class="form-control" placeholder="Comment" rows="4"></textarea>
                    </div>

                    <button class="btn btn-primary btn-block" type="submit">Submit your comment</button>
                </form>

            </div>
        </div>

    </div>
</div>
