<?
	$pagination = $this->macros('system','numpages',array($variables['total'],$variables['per_page']));
    
    if(isset($variables['total']) and isset($variables['per_page']) and $variables['total'] > $variables['per_page']):
?>
<nav>
     
   <?php if(isset($pagination['toprev_link']) and !isset($pagination['tonext_link'])): ?>
                
             
        
            <?php endif; ?>
           
            <?php if(isset($pagination['toprev_link'])): ?>
               
                <a class="btn btn-white" href='<?php echo $pagination['toprev_link']['value'];?>'><i class="ti-arrow-left fs-9 mr-2"></i> Newer</a>
                
            <?php endif; ?>

            <?php if(isset($pagination['tonext_link'])): ?>
                
                <a class="btn btn-white" href='<?php echo $pagination['tonext_link']['value'];?>'>Older <i class="ti-arrow-right fs-9 ml-2"></i></a>  
                
    <?php endif; ?>

  
</nav>
<?endif;?>